//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThermoWeb.Serv_NAVISION_DEBUG {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WSFunctionsAPP", ConfigurationName="Serv_NAVISION_DEBUG.WSFunctionsAPP_Port")]
    public interface WSFunctionsAPP_Port {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de contenedor (ActualizaLinPedCompra_Result) del mensaje ActualizaLinPedCompra_Result no coincide con el valor predeterminado (ActualizaLinPedCompra)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/WSFunctionsAPP:ActualizaLinPedCompra", ReplyAction="*")]
        ThermoWeb.Serv_NAVISION_DEBUG.ActualizaLinPedCompra_Result ActualizaLinPedCompra(ThermoWeb.Serv_NAVISION_DEBUG.ActualizaLinPedCompra request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/WSFunctionsAPP:ActualizaLinPedCompra", ReplyAction="*")]
        System.Threading.Tasks.Task<ThermoWeb.Serv_NAVISION_DEBUG.ActualizaLinPedCompra_Result> ActualizaLinPedCompraAsync(ThermoWeb.Serv_NAVISION_DEBUG.ActualizaLinPedCompra request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de contenedor (ChangeLocationItem_Result) del mensaje ChangeLocationItem_Result no coincide con el valor predeterminado (ChangeLocationItem)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/WSFunctionsAPP:ChangeLocationItem", ReplyAction="*")]
        ThermoWeb.Serv_NAVISION_DEBUG.ChangeLocationItem_Result ChangeLocationItem(ThermoWeb.Serv_NAVISION_DEBUG.ChangeLocationItem request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/WSFunctionsAPP:ChangeLocationItem", ReplyAction="*")]
        System.Threading.Tasks.Task<ThermoWeb.Serv_NAVISION_DEBUG.ChangeLocationItem_Result> ChangeLocationItemAsync(ThermoWeb.Serv_NAVISION_DEBUG.ChangeLocationItem request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de contenedor (CierraPedidoCompra_Result) del mensaje CierraPedidoCompra_Result no coincide con el valor predeterminado (CierraPedidoCompra)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/WSFunctionsAPP:CierraPedidoCompra", ReplyAction="*")]
        ThermoWeb.Serv_NAVISION_DEBUG.CierraPedidoCompra_Result CierraPedidoCompra(ThermoWeb.Serv_NAVISION_DEBUG.CierraPedidoCompra request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/WSFunctionsAPP:CierraPedidoCompra", ReplyAction="*")]
        System.Threading.Tasks.Task<ThermoWeb.Serv_NAVISION_DEBUG.CierraPedidoCompra_Result> CierraPedidoCompraAsync(ThermoWeb.Serv_NAVISION_DEBUG.CierraPedidoCompra request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de contenedor (GeneraAlbaranVentaDesdePedido_Result) del mensaje GeneraAlbaranVentaDesdePedido_Result no coincide con el valor predeterminado (GeneraAlbaranVentaDesdePedido)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/WSFunctionsAPP:GeneraAlbaranVentaDesdePed" +
            "ido", ReplyAction="*")]
        ThermoWeb.Serv_NAVISION_DEBUG.GeneraAlbaranVentaDesdePedido_Result GeneraAlbaranVentaDesdePedido(ThermoWeb.Serv_NAVISION_DEBUG.GeneraAlbaranVentaDesdePedido request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/WSFunctionsAPP:GeneraAlbaranVentaDesdePed" +
            "ido", ReplyAction="*")]
        System.Threading.Tasks.Task<ThermoWeb.Serv_NAVISION_DEBUG.GeneraAlbaranVentaDesdePedido_Result> GeneraAlbaranVentaDesdePedidoAsync(ThermoWeb.Serv_NAVISION_DEBUG.GeneraAlbaranVentaDesdePedido request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de contenedor (GetProducto_Result) del mensaje GetProducto_Result no coincide con el valor predeterminado (GetProducto)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/WSFunctionsAPP:GetProducto", ReplyAction="*")]
        ThermoWeb.Serv_NAVISION_DEBUG.GetProducto_Result GetProducto(ThermoWeb.Serv_NAVISION_DEBUG.GetProducto request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/WSFunctionsAPP:GetProducto", ReplyAction="*")]
        System.Threading.Tasks.Task<ThermoWeb.Serv_NAVISION_DEBUG.GetProducto_Result> GetProductoAsync(ThermoWeb.Serv_NAVISION_DEBUG.GetProducto request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de contenedor (GrabarLineaServicio_Result) del mensaje GrabarLineaServicio_Result no coincide con el valor predeterminado (GrabarLineaServicio)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/WSFunctionsAPP:GrabarLineaServicio", ReplyAction="*")]
        ThermoWeb.Serv_NAVISION_DEBUG.GrabarLineaServicio_Result GrabarLineaServicio(ThermoWeb.Serv_NAVISION_DEBUG.GrabarLineaServicio request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/WSFunctionsAPP:GrabarLineaServicio", ReplyAction="*")]
        System.Threading.Tasks.Task<ThermoWeb.Serv_NAVISION_DEBUG.GrabarLineaServicio_Result> GrabarLineaServicioAsync(ThermoWeb.Serv_NAVISION_DEBUG.GrabarLineaServicio request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de contenedor (ReadStockLocation_Result) del mensaje ReadStockLocation_Result no coincide con el valor predeterminado (ReadStockLocation)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/WSFunctionsAPP:ReadStockLocation", ReplyAction="*")]
        ThermoWeb.Serv_NAVISION_DEBUG.ReadStockLocation_Result ReadStockLocation(ThermoWeb.Serv_NAVISION_DEBUG.ReadStockLocation request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/WSFunctionsAPP:ReadStockLocation", ReplyAction="*")]
        System.Threading.Tasks.Task<ThermoWeb.Serv_NAVISION_DEBUG.ReadStockLocation_Result> ReadStockLocationAsync(ThermoWeb.Serv_NAVISION_DEBUG.ReadStockLocation request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de contenedor (ReadStock_Result) del mensaje ReadStock_Result no coincide con el valor predeterminado (ReadStock)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/WSFunctionsAPP:ReadStock", ReplyAction="*")]
        ThermoWeb.Serv_NAVISION_DEBUG.ReadStock_Result ReadStock(ThermoWeb.Serv_NAVISION_DEBUG.ReadStock request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/WSFunctionsAPP:ReadStock", ReplyAction="*")]
        System.Threading.Tasks.Task<ThermoWeb.Serv_NAVISION_DEBUG.ReadStock_Result> ReadStockAsync(ThermoWeb.Serv_NAVISION_DEBUG.ReadStock request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ActualizaLinPedCompra", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/WSFunctionsAPP", IsWrapped=true)]
    public partial class ActualizaLinPedCompra {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WSFunctionsAPP", Order=0)]
        public string pedidoCompra;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WSFunctionsAPP", Order=1)]
        public int linCompra;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WSFunctionsAPP", Order=2)]
        public decimal qty_to_Receive;
        
        public ActualizaLinPedCompra() {
        }
        
        public ActualizaLinPedCompra(string pedidoCompra, int linCompra, decimal qty_to_Receive) {
            this.pedidoCompra = pedidoCompra;
            this.linCompra = linCompra;
            this.qty_to_Receive = qty_to_Receive;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ActualizaLinPedCompra_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/WSFunctionsAPP", IsWrapped=true)]
    public partial class ActualizaLinPedCompra_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WSFunctionsAPP", Order=0)]
        public string return_value;
        
        public ActualizaLinPedCompra_Result() {
        }
        
        public ActualizaLinPedCompra_Result(string return_value) {
            this.return_value = return_value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ChangeLocationItem", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/WSFunctionsAPP", IsWrapped=true)]
    public partial class ChangeLocationItem {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WSFunctionsAPP", Order=0)]
        public string pItem;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WSFunctionsAPP", Order=1)]
        public string pLocationIni;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WSFunctionsAPP", Order=2)]
        public string pLocationFin;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WSFunctionsAPP", Order=3)]
        public decimal pQuantity;
        
        public ChangeLocationItem() {
        }
        
        public ChangeLocationItem(string pItem, string pLocationIni, string pLocationFin, decimal pQuantity) {
            this.pItem = pItem;
            this.pLocationIni = pLocationIni;
            this.pLocationFin = pLocationFin;
            this.pQuantity = pQuantity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ChangeLocationItem_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/WSFunctionsAPP", IsWrapped=true)]
    public partial class ChangeLocationItem_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WSFunctionsAPP", Order=0)]
        public string return_value;
        
        public ChangeLocationItem_Result() {
        }
        
        public ChangeLocationItem_Result(string return_value) {
            this.return_value = return_value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CierraPedidoCompra", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/WSFunctionsAPP", IsWrapped=true)]
    public partial class CierraPedidoCompra {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WSFunctionsAPP", Order=0)]
        public string pedidoCompra;
        
        public CierraPedidoCompra() {
        }
        
        public CierraPedidoCompra(string pedidoCompra) {
            this.pedidoCompra = pedidoCompra;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CierraPedidoCompra_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/WSFunctionsAPP", IsWrapped=true)]
    public partial class CierraPedidoCompra_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WSFunctionsAPP", Order=0)]
        public string return_value;
        
        public CierraPedidoCompra_Result() {
        }
        
        public CierraPedidoCompra_Result(string return_value) {
            this.return_value = return_value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GeneraAlbaranVentaDesdePedido", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/WSFunctionsAPP", IsWrapped=true)]
    public partial class GeneraAlbaranVentaDesdePedido {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WSFunctionsAPP", Order=0)]
        public string pedido;
        
        public GeneraAlbaranVentaDesdePedido() {
        }
        
        public GeneraAlbaranVentaDesdePedido(string pedido) {
            this.pedido = pedido;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GeneraAlbaranVentaDesdePedido_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/WSFunctionsAPP", IsWrapped=true)]
    public partial class GeneraAlbaranVentaDesdePedido_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WSFunctionsAPP", Order=0)]
        public string return_value;
        
        public GeneraAlbaranVentaDesdePedido_Result() {
        }
        
        public GeneraAlbaranVentaDesdePedido_Result(string return_value) {
            this.return_value = return_value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetProducto", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/WSFunctionsAPP", IsWrapped=true)]
    public partial class GetProducto {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WSFunctionsAPP", Order=0)]
        public string no;
        
        public GetProducto() {
        }
        
        public GetProducto(string no) {
            this.no = no;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetProducto_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/WSFunctionsAPP", IsWrapped=true)]
    public partial class GetProducto_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WSFunctionsAPP", Order=0)]
        public string return_value;
        
        public GetProducto_Result() {
        }
        
        public GetProducto_Result(string return_value) {
            this.return_value = return_value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GrabarLineaServicio", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/WSFunctionsAPP", IsWrapped=true)]
    public partial class GrabarLineaServicio {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WSFunctionsAPP", Order=0)]
        public string pDocumento;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WSFunctionsAPP", Order=1)]
        public decimal cantidad;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WSFunctionsAPP", Order=2)]
        public decimal tipo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WSFunctionsAPP", Order=3)]
        public string codigo;
        
        public GrabarLineaServicio() {
        }
        
        public GrabarLineaServicio(string pDocumento, decimal cantidad, decimal tipo, string codigo) {
            this.pDocumento = pDocumento;
            this.cantidad = cantidad;
            this.tipo = tipo;
            this.codigo = codigo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GrabarLineaServicio_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/WSFunctionsAPP", IsWrapped=true)]
    public partial class GrabarLineaServicio_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WSFunctionsAPP", Order=0)]
        public string return_value;
        
        public GrabarLineaServicio_Result() {
        }
        
        public GrabarLineaServicio_Result(string return_value) {
            this.return_value = return_value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadStockLocation", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/WSFunctionsAPP", IsWrapped=true)]
    public partial class ReadStockLocation {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WSFunctionsAPP", Order=0)]
        public string pLocation;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WSFunctionsAPP", Order=1)]
        public string includeNegatives;
        
        public ReadStockLocation() {
        }
        
        public ReadStockLocation(string pLocation, string includeNegatives) {
            this.pLocation = pLocation;
            this.includeNegatives = includeNegatives;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadStockLocation_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/WSFunctionsAPP", IsWrapped=true)]
    public partial class ReadStockLocation_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WSFunctionsAPP", Order=0)]
        public string return_value;
        
        public ReadStockLocation_Result() {
        }
        
        public ReadStockLocation_Result(string return_value) {
            this.return_value = return_value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadStock", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/WSFunctionsAPP", IsWrapped=true)]
    public partial class ReadStock {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WSFunctionsAPP", Order=0)]
        public string pItem;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WSFunctionsAPP", Order=1)]
        public string pLocation;
        
        public ReadStock() {
        }
        
        public ReadStock(string pItem, string pLocation) {
            this.pItem = pItem;
            this.pLocation = pLocation;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadStock_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/WSFunctionsAPP", IsWrapped=true)]
    public partial class ReadStock_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WSFunctionsAPP", Order=0)]
        public string return_value;
        
        public ReadStock_Result() {
        }
        
        public ReadStock_Result(string return_value) {
            this.return_value = return_value;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSFunctionsAPP_PortChannel : ThermoWeb.Serv_NAVISION_DEBUG.WSFunctionsAPP_Port, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSFunctionsAPP_PortClient : System.ServiceModel.ClientBase<ThermoWeb.Serv_NAVISION_DEBUG.WSFunctionsAPP_Port>, ThermoWeb.Serv_NAVISION_DEBUG.WSFunctionsAPP_Port {
        
        public WSFunctionsAPP_PortClient() {
        }
        
        public WSFunctionsAPP_PortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSFunctionsAPP_PortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSFunctionsAPP_PortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSFunctionsAPP_PortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ThermoWeb.Serv_NAVISION_DEBUG.ActualizaLinPedCompra_Result ThermoWeb.Serv_NAVISION_DEBUG.WSFunctionsAPP_Port.ActualizaLinPedCompra(ThermoWeb.Serv_NAVISION_DEBUG.ActualizaLinPedCompra request) {
            return base.Channel.ActualizaLinPedCompra(request);
        }
        
        public string ActualizaLinPedCompra(string pedidoCompra, int linCompra, decimal qty_to_Receive) {
            ThermoWeb.Serv_NAVISION_DEBUG.ActualizaLinPedCompra inValue = new ThermoWeb.Serv_NAVISION_DEBUG.ActualizaLinPedCompra();
            inValue.pedidoCompra = pedidoCompra;
            inValue.linCompra = linCompra;
            inValue.qty_to_Receive = qty_to_Receive;
            ThermoWeb.Serv_NAVISION_DEBUG.ActualizaLinPedCompra_Result retVal = ((ThermoWeb.Serv_NAVISION_DEBUG.WSFunctionsAPP_Port)(this)).ActualizaLinPedCompra(inValue);
            return retVal.return_value;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ThermoWeb.Serv_NAVISION_DEBUG.ActualizaLinPedCompra_Result> ThermoWeb.Serv_NAVISION_DEBUG.WSFunctionsAPP_Port.ActualizaLinPedCompraAsync(ThermoWeb.Serv_NAVISION_DEBUG.ActualizaLinPedCompra request) {
            return base.Channel.ActualizaLinPedCompraAsync(request);
        }
        
        public System.Threading.Tasks.Task<ThermoWeb.Serv_NAVISION_DEBUG.ActualizaLinPedCompra_Result> ActualizaLinPedCompraAsync(string pedidoCompra, int linCompra, decimal qty_to_Receive) {
            ThermoWeb.Serv_NAVISION_DEBUG.ActualizaLinPedCompra inValue = new ThermoWeb.Serv_NAVISION_DEBUG.ActualizaLinPedCompra();
            inValue.pedidoCompra = pedidoCompra;
            inValue.linCompra = linCompra;
            inValue.qty_to_Receive = qty_to_Receive;
            return ((ThermoWeb.Serv_NAVISION_DEBUG.WSFunctionsAPP_Port)(this)).ActualizaLinPedCompraAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ThermoWeb.Serv_NAVISION_DEBUG.ChangeLocationItem_Result ThermoWeb.Serv_NAVISION_DEBUG.WSFunctionsAPP_Port.ChangeLocationItem(ThermoWeb.Serv_NAVISION_DEBUG.ChangeLocationItem request) {
            return base.Channel.ChangeLocationItem(request);
        }
        
        public string ChangeLocationItem(string pItem, string pLocationIni, string pLocationFin, decimal pQuantity) {
            ThermoWeb.Serv_NAVISION_DEBUG.ChangeLocationItem inValue = new ThermoWeb.Serv_NAVISION_DEBUG.ChangeLocationItem();
            inValue.pItem = pItem;
            inValue.pLocationIni = pLocationIni;
            inValue.pLocationFin = pLocationFin;
            inValue.pQuantity = pQuantity;
            ThermoWeb.Serv_NAVISION_DEBUG.ChangeLocationItem_Result retVal = ((ThermoWeb.Serv_NAVISION_DEBUG.WSFunctionsAPP_Port)(this)).ChangeLocationItem(inValue);
            return retVal.return_value;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ThermoWeb.Serv_NAVISION_DEBUG.ChangeLocationItem_Result> ThermoWeb.Serv_NAVISION_DEBUG.WSFunctionsAPP_Port.ChangeLocationItemAsync(ThermoWeb.Serv_NAVISION_DEBUG.ChangeLocationItem request) {
            return base.Channel.ChangeLocationItemAsync(request);
        }
        
        public System.Threading.Tasks.Task<ThermoWeb.Serv_NAVISION_DEBUG.ChangeLocationItem_Result> ChangeLocationItemAsync(string pItem, string pLocationIni, string pLocationFin, decimal pQuantity) {
            ThermoWeb.Serv_NAVISION_DEBUG.ChangeLocationItem inValue = new ThermoWeb.Serv_NAVISION_DEBUG.ChangeLocationItem();
            inValue.pItem = pItem;
            inValue.pLocationIni = pLocationIni;
            inValue.pLocationFin = pLocationFin;
            inValue.pQuantity = pQuantity;
            return ((ThermoWeb.Serv_NAVISION_DEBUG.WSFunctionsAPP_Port)(this)).ChangeLocationItemAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ThermoWeb.Serv_NAVISION_DEBUG.CierraPedidoCompra_Result ThermoWeb.Serv_NAVISION_DEBUG.WSFunctionsAPP_Port.CierraPedidoCompra(ThermoWeb.Serv_NAVISION_DEBUG.CierraPedidoCompra request) {
            return base.Channel.CierraPedidoCompra(request);
        }
        
        public string CierraPedidoCompra(string pedidoCompra) {
            ThermoWeb.Serv_NAVISION_DEBUG.CierraPedidoCompra inValue = new ThermoWeb.Serv_NAVISION_DEBUG.CierraPedidoCompra();
            inValue.pedidoCompra = pedidoCompra;
            ThermoWeb.Serv_NAVISION_DEBUG.CierraPedidoCompra_Result retVal = ((ThermoWeb.Serv_NAVISION_DEBUG.WSFunctionsAPP_Port)(this)).CierraPedidoCompra(inValue);
            return retVal.return_value;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ThermoWeb.Serv_NAVISION_DEBUG.CierraPedidoCompra_Result> ThermoWeb.Serv_NAVISION_DEBUG.WSFunctionsAPP_Port.CierraPedidoCompraAsync(ThermoWeb.Serv_NAVISION_DEBUG.CierraPedidoCompra request) {
            return base.Channel.CierraPedidoCompraAsync(request);
        }
        
        public System.Threading.Tasks.Task<ThermoWeb.Serv_NAVISION_DEBUG.CierraPedidoCompra_Result> CierraPedidoCompraAsync(string pedidoCompra) {
            ThermoWeb.Serv_NAVISION_DEBUG.CierraPedidoCompra inValue = new ThermoWeb.Serv_NAVISION_DEBUG.CierraPedidoCompra();
            inValue.pedidoCompra = pedidoCompra;
            return ((ThermoWeb.Serv_NAVISION_DEBUG.WSFunctionsAPP_Port)(this)).CierraPedidoCompraAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ThermoWeb.Serv_NAVISION_DEBUG.GeneraAlbaranVentaDesdePedido_Result ThermoWeb.Serv_NAVISION_DEBUG.WSFunctionsAPP_Port.GeneraAlbaranVentaDesdePedido(ThermoWeb.Serv_NAVISION_DEBUG.GeneraAlbaranVentaDesdePedido request) {
            return base.Channel.GeneraAlbaranVentaDesdePedido(request);
        }
        
        public string GeneraAlbaranVentaDesdePedido(string pedido) {
            ThermoWeb.Serv_NAVISION_DEBUG.GeneraAlbaranVentaDesdePedido inValue = new ThermoWeb.Serv_NAVISION_DEBUG.GeneraAlbaranVentaDesdePedido();
            inValue.pedido = pedido;
            ThermoWeb.Serv_NAVISION_DEBUG.GeneraAlbaranVentaDesdePedido_Result retVal = ((ThermoWeb.Serv_NAVISION_DEBUG.WSFunctionsAPP_Port)(this)).GeneraAlbaranVentaDesdePedido(inValue);
            return retVal.return_value;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ThermoWeb.Serv_NAVISION_DEBUG.GeneraAlbaranVentaDesdePedido_Result> ThermoWeb.Serv_NAVISION_DEBUG.WSFunctionsAPP_Port.GeneraAlbaranVentaDesdePedidoAsync(ThermoWeb.Serv_NAVISION_DEBUG.GeneraAlbaranVentaDesdePedido request) {
            return base.Channel.GeneraAlbaranVentaDesdePedidoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ThermoWeb.Serv_NAVISION_DEBUG.GeneraAlbaranVentaDesdePedido_Result> GeneraAlbaranVentaDesdePedidoAsync(string pedido) {
            ThermoWeb.Serv_NAVISION_DEBUG.GeneraAlbaranVentaDesdePedido inValue = new ThermoWeb.Serv_NAVISION_DEBUG.GeneraAlbaranVentaDesdePedido();
            inValue.pedido = pedido;
            return ((ThermoWeb.Serv_NAVISION_DEBUG.WSFunctionsAPP_Port)(this)).GeneraAlbaranVentaDesdePedidoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ThermoWeb.Serv_NAVISION_DEBUG.GetProducto_Result ThermoWeb.Serv_NAVISION_DEBUG.WSFunctionsAPP_Port.GetProducto(ThermoWeb.Serv_NAVISION_DEBUG.GetProducto request) {
            return base.Channel.GetProducto(request);
        }
        
        public string GetProducto(string no) {
            ThermoWeb.Serv_NAVISION_DEBUG.GetProducto inValue = new ThermoWeb.Serv_NAVISION_DEBUG.GetProducto();
            inValue.no = no;
            ThermoWeb.Serv_NAVISION_DEBUG.GetProducto_Result retVal = ((ThermoWeb.Serv_NAVISION_DEBUG.WSFunctionsAPP_Port)(this)).GetProducto(inValue);
            return retVal.return_value;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ThermoWeb.Serv_NAVISION_DEBUG.GetProducto_Result> ThermoWeb.Serv_NAVISION_DEBUG.WSFunctionsAPP_Port.GetProductoAsync(ThermoWeb.Serv_NAVISION_DEBUG.GetProducto request) {
            return base.Channel.GetProductoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ThermoWeb.Serv_NAVISION_DEBUG.GetProducto_Result> GetProductoAsync(string no) {
            ThermoWeb.Serv_NAVISION_DEBUG.GetProducto inValue = new ThermoWeb.Serv_NAVISION_DEBUG.GetProducto();
            inValue.no = no;
            return ((ThermoWeb.Serv_NAVISION_DEBUG.WSFunctionsAPP_Port)(this)).GetProductoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ThermoWeb.Serv_NAVISION_DEBUG.GrabarLineaServicio_Result ThermoWeb.Serv_NAVISION_DEBUG.WSFunctionsAPP_Port.GrabarLineaServicio(ThermoWeb.Serv_NAVISION_DEBUG.GrabarLineaServicio request) {
            return base.Channel.GrabarLineaServicio(request);
        }
        
        public string GrabarLineaServicio(string pDocumento, decimal cantidad, decimal tipo, string codigo) {
            ThermoWeb.Serv_NAVISION_DEBUG.GrabarLineaServicio inValue = new ThermoWeb.Serv_NAVISION_DEBUG.GrabarLineaServicio();
            inValue.pDocumento = pDocumento;
            inValue.cantidad = cantidad;
            inValue.tipo = tipo;
            inValue.codigo = codigo;
            ThermoWeb.Serv_NAVISION_DEBUG.GrabarLineaServicio_Result retVal = ((ThermoWeb.Serv_NAVISION_DEBUG.WSFunctionsAPP_Port)(this)).GrabarLineaServicio(inValue);
            return retVal.return_value;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ThermoWeb.Serv_NAVISION_DEBUG.GrabarLineaServicio_Result> ThermoWeb.Serv_NAVISION_DEBUG.WSFunctionsAPP_Port.GrabarLineaServicioAsync(ThermoWeb.Serv_NAVISION_DEBUG.GrabarLineaServicio request) {
            return base.Channel.GrabarLineaServicioAsync(request);
        }
        
        public System.Threading.Tasks.Task<ThermoWeb.Serv_NAVISION_DEBUG.GrabarLineaServicio_Result> GrabarLineaServicioAsync(string pDocumento, decimal cantidad, decimal tipo, string codigo) {
            ThermoWeb.Serv_NAVISION_DEBUG.GrabarLineaServicio inValue = new ThermoWeb.Serv_NAVISION_DEBUG.GrabarLineaServicio();
            inValue.pDocumento = pDocumento;
            inValue.cantidad = cantidad;
            inValue.tipo = tipo;
            inValue.codigo = codigo;
            return ((ThermoWeb.Serv_NAVISION_DEBUG.WSFunctionsAPP_Port)(this)).GrabarLineaServicioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ThermoWeb.Serv_NAVISION_DEBUG.ReadStockLocation_Result ThermoWeb.Serv_NAVISION_DEBUG.WSFunctionsAPP_Port.ReadStockLocation(ThermoWeb.Serv_NAVISION_DEBUG.ReadStockLocation request) {
            return base.Channel.ReadStockLocation(request);
        }
        
        public string ReadStockLocation(string pLocation, string includeNegatives) {
            ThermoWeb.Serv_NAVISION_DEBUG.ReadStockLocation inValue = new ThermoWeb.Serv_NAVISION_DEBUG.ReadStockLocation();
            inValue.pLocation = pLocation;
            inValue.includeNegatives = includeNegatives;
            ThermoWeb.Serv_NAVISION_DEBUG.ReadStockLocation_Result retVal = ((ThermoWeb.Serv_NAVISION_DEBUG.WSFunctionsAPP_Port)(this)).ReadStockLocation(inValue);
            return retVal.return_value;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ThermoWeb.Serv_NAVISION_DEBUG.ReadStockLocation_Result> ThermoWeb.Serv_NAVISION_DEBUG.WSFunctionsAPP_Port.ReadStockLocationAsync(ThermoWeb.Serv_NAVISION_DEBUG.ReadStockLocation request) {
            return base.Channel.ReadStockLocationAsync(request);
        }
        
        public System.Threading.Tasks.Task<ThermoWeb.Serv_NAVISION_DEBUG.ReadStockLocation_Result> ReadStockLocationAsync(string pLocation, string includeNegatives) {
            ThermoWeb.Serv_NAVISION_DEBUG.ReadStockLocation inValue = new ThermoWeb.Serv_NAVISION_DEBUG.ReadStockLocation();
            inValue.pLocation = pLocation;
            inValue.includeNegatives = includeNegatives;
            return ((ThermoWeb.Serv_NAVISION_DEBUG.WSFunctionsAPP_Port)(this)).ReadStockLocationAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ThermoWeb.Serv_NAVISION_DEBUG.ReadStock_Result ThermoWeb.Serv_NAVISION_DEBUG.WSFunctionsAPP_Port.ReadStock(ThermoWeb.Serv_NAVISION_DEBUG.ReadStock request) {
            return base.Channel.ReadStock(request);
        }
        
        public string ReadStock(string pItem, string pLocation) {
            ThermoWeb.Serv_NAVISION_DEBUG.ReadStock inValue = new ThermoWeb.Serv_NAVISION_DEBUG.ReadStock();
            inValue.pItem = pItem;
            inValue.pLocation = pLocation;
            ThermoWeb.Serv_NAVISION_DEBUG.ReadStock_Result retVal = ((ThermoWeb.Serv_NAVISION_DEBUG.WSFunctionsAPP_Port)(this)).ReadStock(inValue);
            return retVal.return_value;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ThermoWeb.Serv_NAVISION_DEBUG.ReadStock_Result> ThermoWeb.Serv_NAVISION_DEBUG.WSFunctionsAPP_Port.ReadStockAsync(ThermoWeb.Serv_NAVISION_DEBUG.ReadStock request) {
            return base.Channel.ReadStockAsync(request);
        }
        
        public System.Threading.Tasks.Task<ThermoWeb.Serv_NAVISION_DEBUG.ReadStock_Result> ReadStockAsync(string pItem, string pLocation) {
            ThermoWeb.Serv_NAVISION_DEBUG.ReadStock inValue = new ThermoWeb.Serv_NAVISION_DEBUG.ReadStock();
            inValue.pItem = pItem;
            inValue.pLocation = pLocation;
            return ((ThermoWeb.Serv_NAVISION_DEBUG.WSFunctionsAPP_Port)(this)).ReadStockAsync(inValue);
        }
    }
}
